print("Hello World")
name = input("Enter your Name: ")
print("Hello %s" % name)
print("jet malupet")
print("hHAHAHAHAHAH")
print("hHAHAHAHAHAH")
print("hHAHAHAHAHAH")
print("hHAHAHAHAHAH")
print("hHAHAHAHAHAH")
